name: 'Annotate'
description: 'Annotate a new tag (e.g. on tracking platform)'

inputs:
  tag:
    description: 'Tag name to annotate'
    required: true
  mixpanel-project-id:
    description: 'Mixpanel Project ID'
    required: false
  mixpanel-token:
    description: 'Mixpanel Token (Basic Auth)'
    required: false
  mixpanel-region-domain:
    description: 'Mixpanel Region Domain'
    required: false
    default: 'mixpanel'

runs:
  using: "composite"
  steps:

    - name: Create Mixpanel Annotation
      if: inputs.mixpanel-project-id != '' && inputs.mixpanel-token != ''
      shell: bash
      # https://developer.mixpanel.com/reference/create-annotation-tag-1
      run: |
        curl --request POST \
          --url "https://${{ inputs.mixpanel-region-domain }}.com/api/app/projects/${{ inputs.mixpanel-project-id }}/annotations/tags" \
          --header "accept: application/json" \
          --header "authorization: Basic ${{ inputs.mixpanel-token }}" \
          --header "content-type: application/json" \
          --data '{"name":"${{ inputs.tag }}"}'

        curlExitCode=$?
        echo "Annotation created on Mixpanel for tag: ${{ inputs.tag }}"
        exit $curlExitCode
